### ISSUE TITLE
TE-analysis_Shuffle_bed.pl  errors

### ISSUE THREAD

**Issue by JinfengChen** [4ureliek/TEanalysis#1]
Hi Aurelie,
I am playing with TE-analysis_Shuffle_bed.pl to test enrichment of TE in chip seq peaks. The script report errors "WARN: no value for total number (from RM output), for {age}{cat.1}{tot}? => no binomial test". I checked the result file "H3K4me3_peaks.1.bed.boot.age1" and found one column is empty. I shared my input files to you (https://github.com/JinfengChen/TE_analysis/blob/master/test.tar.gz). Can you please take a look and help with the input format? Thanks.

Jinfeng

File with empty column:
H3K4me3_peaks.1.bed.boot.age1
boot.1	age	cat.1	tot		31562	31562	20014
boot.2	age	cat.1	tot		31562	31562	1989

command line:
perl ./Utils/TE-analysis_Shuffle_bed.pl -f H3K4me3_peaks.1.bed -s MSU_r7.fa.RepeatMasker.class.nonTE-none.bed -r MSU_r7.fa.build.tab -e MSU_r7.fa.gaps.bed -n 10

**Comment by 4ureliek** [comment]
Hi,
The age categories should only be considered if a file with the age info for the TEs is provided with -g,--group. You can ignore this error and look at the rest of the results - it should not be a die/kill error. I will update shortly a fixed version.
Cheers,
Aurelie

**Comment by 4ureliek** [comment]
I updated a fixed version - please let me know if you still get errors!

**Comment by JinfengChen** [comment]
Thanks, Aurelie. I updated the script and it works fine now. I found out the cause of my failure is the version of Statistics::R. I used 0.2 but 0.34 is the right version.
Best.

Jinfeng
