### ISSUE TITLE
TE-analysis_Shuffle_bed.pl_V4.4 error

### ISSUE THREAD

**Issue by wolfQK** [4ureliek/TEanalysis#2]
Hi Aurelie,
I am playing with TE-analysis_Shuffle_bed.pl to test enrichment of TE in ATACseq peaks. The script reports errors"Invalid version format (non-numeric data) at /zfssz2/Perl/lib/perl5/site_perl/5.26.1/Statistics/R.pm line 369.".
Can you take a look and help me with this problem? Thank you very much!
My command is the following:
perl /zfssz2/script/TEanalysis-master/TE-analysis_Shuffle_bed.pl 
-q /zfssz2/mydata/TE_hg38_class/5_s.bed 
-f /zfssz2/mydata/Neural_ATAC_hg38/t-iPS129.EB.68.stage.bed 
-s bed  
-r /zfssz2/mydata/hg38.chrom.sizes 
-e /zfssz2/mydata/gap.txt.bed  
-w /zfssz2/software/bedtools2/bedtools2/bin/
-o 1 -n 100 
Besides,the two bed files are both 3 columns(chr start end).

**Comment by 4ureliek** [comment]
Hi,
This is an error in the R module itself; you should have in the error message the line where the R module is called in my code, that would be very helpful (I need to know why something non numerical was passed to the R module). Even better for me to debug is if you share with me small files that reproduce the error!
Cheers,
Aurelie

**Comment by 4ureliek** [comment]
I just tried a test run with a fake input file being a bunch of mouse mm10 TEs, and got no errors - so I definitely need sample files to be able to help you out!
Quick question though, is this file: `/zfssz2/mydata/TE_hg38_class/5_s.bed` a repeat masker output file? Even if in bed format, the code is written to parse repeat masker output info, so if not that could be the source of the issue.

**Comment by wolfQK** [comment]
Hi Aurelie,
  Thank you for your prompt reply. There is no flaw in your code, I use the wrong type of file, which is a subset of repeat masker output file. And my problem has been solved. Thank you!
