### ISSUE TITLE
Error in running TE-analysis_Shuffle_bed.pl

### ISSUE THREAD

**Issue by AAli-90** [4ureliek/TEanalysis#4]
Hi Aurelie,
I was trying to run TE-analysis_Shuffle_bed.pl
This is my command line: 
perl TE-analysis_Shuffle_bed.pl -f input.bed -q hg38.fa.out -r hg38.chrom.sizes -s rm
and I got this error:
syntax error at TE-analysis_Shuffle_bed.pl line 10, near "<"
Excessively long <> operator at TE-analysis_Shuffle_bed.pl line 21.
Input.bed has 3 columns (chr, start and end), hg38.fa.out is the repeat masker .out file and hg38.chrom.sizes is from UCSC.
Is there something wrong with my files or the script? Would you help me with this?
Thank you

**Comment by 4ureliek** [comment]
Can you check the file that you are running? There isn't any "<" at line 10 in the code...! Please make sure it was downloaded/cloned properly?

**Comment by AAli-90** [comment]
Yes actually I didn't download it the right way. 
Thank you

**Comment by AAli-90** [comment]
Hi,
Yes I made mistake while downloading. Thank you so much for your response.
Arsala
