### ISSUE TITLE
How to evaluate significance based on binomial_test？

### ISSUE THREAD

**Issue by woshiyangsi** [4ureliek/TEanalysis#7]
Hi @4ureliek,

I tried to evaluate the significance based on two tailed permutation test, so I used rank is > 5 and pvalue is not "ns" to filter, but I did not get significant TEs.
Therefore, I want to filter TE based on binomial_test, which conditions should I filter based on at this time? Should I filter directly based on p value?

Looking forward to your reply,
Siyu

**Comment by 4ureliek** [comment]
Hi,
I am not a strong statistician - I would tend to think that if your permutation pvalues are not significant, then you might want to try more bootstraps? Otherwise yes you can filter on binomial_test pvalues, but they may be less reliable.
