### ISSUE TITLE
The output file no_boot.joined

### ISSUE THREAD

**Issue by woshiyangsi** [4ureliek/TEanalysis#8]
Hi,
is  no_boot.joined file are include reference significant TE position and my bed file peak position in the genome?
what is the colname mean of no_boot.joined file?
![image](https://user-images.githubusercontent.com/54662832/180453309-b28be660-6323-47e5-bb94-44fa7cd60ec8.png)

Looking forward to your reply,
Thanks

**Comment by 4ureliek** [comment]
It has been a while so I had to go check out the code; this file is the direct output of intersectBed command line -- look for the line in the log where it is printed. It uses the `-wo` options, so it outputs all original coordinates of overlapping coordinates (see [bedtools documentation here for more details](https://bedtools.readthedocs.io/en/latest/content/tools/intersect.html)).
In your example, the first line shows that this SINE TE overlaps with your provided bed file interval chr1:894998-895499 (and the last column is the length of the overlap)

**Comment by woshiyangsi** [comment]
Thanks
